To Review after 13 sprint
AlexMargina/PlaylistMaker pull request #7
Opened 2023-07-20 20:15 UTC by AlexMargina

Критерии успешного выполнения задания:

1. Переход на экран «Аудиоплеер» при нажатии на элемент списка найденных песен или историю поиска.
2. Если приложение было переведено в фоновый режим на экране «Аудиоплеер», то после восстановления приложения из фонового режима пользователь видит экран «Аудиоплеер».
3. При нажатии на системную кнопку «Назад» или применение аналогичного жеста возвращает пользователя на предыдущий экран.
4. UI экрана аудиоплеера. На экране аудиоплеера пользователь видит следующие UI-элементы:
 - Кнопку «Назад» (нажатие на неё эквивалентно нажатию системной кнопки «Назад»),
 - Область для отображения обложки плеера,
 - Название трека (trackName),
 - Имя исполнителя (artistName),
 - Название альбома (collectionName) (если есть),
 - Год релиза трека (releaseDate),
 - Жанр трека (primaryGenreName),
 - Страна исполнителя (country),
 - Продолжительность трека в формате mm:ss (trackTimeMills),
 - Кнопка добавления в плейлист,
 - Кнопка добавления в избранное,
 - Кнопка контроля воспроизведения,
 - Прогресс воспроизведения (время под кнопкой контроля воспроизведения в формате mm:ss).

6. Плейсхолдер обложки в плеере (если у трека нет изображения обложки или оно ещё не загружено)
7. Изображение обложки в плеере (если у трека есть изображение обложки и оно загружено приложением). В качестве изображения обложки следует использовать изображение, находящееся по ссылке параметра artworkUrl100 с заменой последней части ссылки на 512x512bb.jpg.
 
На экране не требуется реализовывать никакие обработки нажатий, кроме кнопки «Назад». Под кнопкой Play отображается прогресс произведения.

2023-07-21 18:06 UTC, dmitrijegorov requested changes

2023-07-21 18:06 UTC, dmitrijegorov commented on app/src/main/java/com/example/playlistmaker/SearchMusicAdapter.kt
Если закомментированный код больше не понадобится, то можно смело его удалять. Вся история изменений хранится в github

2023-07-21 18:06 UTC, dmitrijegorov commented on app/src/main/res/layout/activity_media.xml
Год распарсился некорректно

![Screenshot_20230721_200218](https://github.com/AlexMargina/PlaylistMaker/assets/46870363/6a2f0a3b-fe5b-4275-9744-19342299845d)


В тёмной теме присутствует ненужная обводка у круглых кнопок

![Screenshot_20230721_203408](https://github.com/AlexMargina/PlaylistMaker/assets/46870363/4c3a41cb-8199-4f4a-a87f-4f70b6885f62)

2023-07-21 21:39 UTC, AlexMargina commented on app/src/main/java/com/example/playlistmaker/SearchMusicAdapter.kt
Понял, поудалял

2023-07-21 21:42 UTC, AlexMargina commented on app/src/main/res/layout/activity_media.xml
Год исправил, квадратики под кнопки убрал, отступы исправил, выравнивание названия - по левому краю

2023-07-22 19:39 UTC, dmitrijegorov commented
Левый отступ у исполнителя больше, чем у названия трека

![Screenshot_20230722_215828](https://github.com/AlexMargina/PlaylistMaker/assets/46870363/cfa03221-230d-4ae0-8d94-b319dca71911)

2023-07-22 19:42 UTC, dmitrijegorov commented
Стрелочка назад чёрная

![Screenshot_20230722_215533](https://github.com/AlexMargina/PlaylistMaker/assets/46870363/8ff95fcc-3212-4be2-be20-fe36ada104b7)

2023-07-23 09:47 UTC, AlexMargina commented on app/src/main/res/layout/activity_media.xml
- убрал дополнительный горизонтальный padding, который сдвигает исполнителя вправо.

- поменял прозрачность иконок и в тёмной теме кнопки iv_add, iv_like имеют тёмно-серую заливку.
- добавил вертикальный отступ от исполнителя.
- поправил на экране настроек цвет кнопки назад в тёмной теме.

2023-07-24 00:16 UTC, dmitrijegorov commented
Относительное расположение стрелки и заголовка стоит поменять (как вертикальный отступ, так и расстояние между ними)

![Screenshot_20230724_031405](https://github.com/AlexMargina/PlaylistMaker/assets/46870363/fc849e9d-90d0-4371-b5b1-fd218bcf0fdf)

2023-07-24 00:31 UTC, dmitrijegorov commented on app/src/main/res/layout/activity_media.xml
> +        app:layout_constraintBottom_toTopOf="@id/tv_title"         />
Перед коммитом всегда для каждого файла стоит приводить его к правильному стилю, так как код будут смотреть другие разработчики. В студии это легко делать путём вызова горячей комбинации клавиш (она зависит от ОС), её можно посмотреть в меню Code → Reformat Code

2023-07-24 00:31 UTC, dmitrijegorov commented on app/src/main/res/layout/activity_media.xml
Более продвинутый вариант вёрстки – использование guidelines, barriers. Подробнее про их применение можно почитать на [https://developer.android.com/develop/ui/views/layout/constraint-layout](https://developer.android.com/develop/ui/views/layout/constraint-layout)



<img width="425" alt="Screenshot 2023-07-23 at 13 55 14" src="https://github.com/AlexMargina/PlaylistMaker/assets/46870363/c8849f95-81f6-421f-b2a4-c28fcc44b6cd">

Такие привязки выглядят не совсем стандартно

2023-07-26 13:45 UTC, AlexMargina commented on app/src/main/res/layout/activity_media.xml
> +        app:layout_constraintBottom_toTopOf="@id/tv_title"         />
Сделал для всех файлов

2023-07-26 13:46 UTC, merged

2023-07-26 13:46 UTC, AlexMargina commented
After review Sprint 13. Maded activity_media.xml